export enum Actions {
  UPDATE_COMMENT = 'UPDATE_COMMENT',
  UPDATE_TOKEN = 'UPDATE_TOKEN',
  ME_REQUEST = 'ME_REQUEST',
  ME_REQUEST_SUCCESS = 'ME_REQUEST_SUCCESS',
  ME_REQUEST_ERROR = 'ME_REQUEST_ERROR',
  POSTS_REQUEST = 'POSTS_REQUEST',
  POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS',
  POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR',
  NEXT_AFTER = 'NEXT_AFTER',
  COUNT_LOAD = 'COUNT_LOAD',
  FIRST_LOAD = 'FIRST_LOAD',
  EMPTY_FETCH = 'EMPTY_FETCH'
}
